server:
  port: 8030
spring:
  application:
    name: getway
eureka:
  client:
    service-url:
      dafaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    provider: /p/**
#    给服务提供者 provider 设置映射